sudo: required
services: docker
before_install:
  - docker build -t deepak/multi-cl -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true deepak/multi-cl npm run test

after_success:
  - docker build -t deepak/multi-client ./client
  - docker build -t deepak/multi-nginx ./nginx
  - docker build -t deepak/multi-server ./server
  - docker build -t deepak/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push deepak/multi-client
  - docker push deepak/multi-nginx
  - docker push deepak/multi-worker
  - docker push deepak/multi-server